---
kind: Service
apiVersion: v1
metadata:
  name: zandronum-server1
spec:
  selector:
    app: zandronum-server2
  type: ClusterIP
  ports:
    - port: 10666
      protocol: TCP
      targetPort: 10666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zandronum-server1
  labels:
    app: zandronum-server1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zandronum-server1
  template:
    metadata:
      labels:
        app: zandronum-server1
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: docker-hub
      volumes:
      - name: zandronum-server
        persistentVolumeClaim:
          claimName: pipeline-nextcloud
      nodeName: rancherkube1-worker1
      containers:
        - name: zandonum-server1
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          args: ["survival"]
          env:
            - name: JOIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: JOIN_PASSWORD
                  name: doom
                  optional: false
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RCON_PASSWORD
                  name: doom
                  optional: false
          ports:
          - containerPort: 10666
            hostPort: 10666
            name: 10666tcp106660
            protocol: UDP
          volumeMounts:
          - mountPath: /data
            name: zandronum-server
            subPath: wads
---
kind: Service
apiVersion: v1
metadata:
  name: zandronum-server2
spec:
  selector:
    app: zandronum-server2
  type: ClusterIP
  ports:
    - port: 10667
      protocol: TCP
      targetPort: 10667
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zandronum-server2
  labels:
    app: zandronum-server2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zandronum-server2
  template:
    metadata:
      labels:
        app: zandronum-server2
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: docker-hub
      volumes:
      - name: zandronum-server
        persistentVolumeClaim:
          claimName: pipeline-nextcloud
      nodeName: rancherkube1-worker2
      containers:
        - name: zandronum-server2
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          args: ["invasion"]
          env:
            - name: JOIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: JOIN_PASSWORD
                  name: doom
                  optional: false
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RCON_PASSWORD
                  name: doom
                  optional: false
          ports:
          - containerPort: 10667
            hostPort: 10667
            name: 10667tcp106670
            protocol: UDP
          volumeMounts:
          - mountPath: /data
            name: zandronum-server
            subPath: wads
