---
apiVersion: v1
kind: Pod
metadata:
  name: zandonum-server-coop
spec:
  hostNetwork: true
  imagePullSecrets:
    - name: docker-hub
  volumes:
  - name: zandronum-server
    persistentVolumeClaim:
      claimName: pipeline-nextcloud
  nodeName: rancherkube1-worker1
  containers:
    - name: zandonum-server-coop
      image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
      args: ["coop"]
      volumeMounts:
      - mountPath: /data
        name: zandronum-server
        subPath: wads
      env:
        - name: JOIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: JOIN_PASSWORD
              name: doom
              optional: false
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              key: RCON_PASSWORD
              name: doom
              optional: false
---
apiVersion: v1
kind: Pod
metadata:
  name: zandonum-server-invasion
spec:
  hostNetwork: true
  imagePullSecrets:
    - name: docker-hub
  volumes:
  - name: zandronum-server
    persistentVolumeClaim:
      claimName: pipeline-nextcloud
  nodeName: rancherkube1-worker2
  containers:
    - name: zandonum-server-invasion
      image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
      args: ["invasion"]
      volumeMounts:
      - mountPath: /data
        name: zandronum-server
        subPath: wads
      env:
        - name: JOIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: JOIN_PASSWORD
              name: doom
              optional: false
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              key: RCON_PASSWORD
              name: doom
              optional: false
